package project.pipepipe.extractor.services.bilibili

object BiliBiliLinks {
    const val WWW_REFERER = "https://www.bilibili.com/"
    const val SPACE_REFERER = "https://space.bilibili.com/"
    const val LIVE_REFERER = "https://live.bilibili.com/"

    const val CHANNEL_BASE_URL = "https://space.bilibili.com/"
    const val VIDEO_BASE_URL = "https://www.bilibili.com/video/"
    const val FREE_VIDEO_API_URL = "https://api.bilibili.com/x/player/wbi/playurl"
    const val PAID_VIDEO_API_URL = "https://api.bilibili.com/pgc/player/web/v2/playurl"
    const val LIVE_BASE_URL = "live.bilibili.com"
    const val QUERY_VIDEO_BULLET_COMMENTS_URL = "https://api.bilibili.com/x/v1/dm/list.so?oid="
    const val QUERY_USER_INFO_URL = "https://api.bilibili.com/x/web-interface/card?photo=true&mid="
    const val QUERY_LIVEROOM_STATUS_URL = "https://api.live.bilibili.com/room/v1/Room/get_status_info_by_uids?uids[]="
    const val QUERY_DANMU_INFO_URL = "https://api.live.bilibili.com/xlive/web-room/v1/index/getDanmuInfo?type=0&id="
    const val GET_SEASON_ARCHIVES_LIST_RAW_URL = "https://api.bilibili.com/x/polymer/web-space/seasons_archives_list?mid=%s&season_id=%s&sort_reverse=false&name=%s&page_num=1&page_size=30"
    const val GET_SERIES_RAW_URL = "https://api.bilibili.com/x/series/archives?mid=%s&series_id=%s&only_normal=true&sort=desc&name=%s&pn=1&ps=30"
    const val GET_SERIES_BASE_URL = "https://api.bilibili.com/x/series/archives"
    const val GET_SEASON_ARCHIVES_LIST_BASE_URL = "https://api.bilibili.com/x/polymer/web-space/seasons_series_list"
    const val GET_SEASON_ARCHIVES_ARCHIVE_BASE_URL = "https://api.bilibili.com/x/polymer/web-space/seasons_archives_list"
    const val GET_SUGGESTION_URL = "https://s.search.bilibili.com/main/suggest?term="
    const val GET_RELATED_URL = "https://api.bilibili.com/x/web-interface/archive/related?bvid="
    const val COMMENT_REPLIES_URL = "https://api.bilibili.com/x/v2/reply/reply?type=1&ps=10&pn=1&web_location=333.788&oid="
    const val GET_SUBTITLE_META_URL = "https://api.bilibili.com/x/player/wbi/v2"
    const val QUERY_USER_VIDEOS_WEB_API_URL = "https://api.bilibili.com/x/space/wbi/arc/search"
    const val QUERY_USER_VIDEOS_CLIENT_API_URL = "https://app.bilibili.com/x/v2/space/archive/cursor"
    const val WBI_IMG_URL = "https://api.bilibili.com/x/web-interface/nav"
    const val GET_PARTITION_URL = "https://api.bilibili.com/x/player/pagelist?bvid="
    const val FETCH_COOKIE_URL = "https://api.bilibili.com/x/frontend/finger/spi"
    const val FETCH_COMMENTS_URL = "https://api.bilibili.com/x/v2/reply/wbi/main"
    const val FETCH_TAGS_URL = "https://api.bilibili.com/x/web-interface/view/detail/tag?bvid="
    const val FETCH_RECOMMENDED_LIVES_URL = "https://api.live.bilibili.com/xlive/web-interface/v1/second/getUserRecommend?page_size=30&platform=web"
    const val FETCH_RECOMMENDED_VIDEOS_URL = "https://www.bilibili.com"
    const val FETCH_TOP_100_URL = "https://api.bilibili.com/x/web-interface/ranking/v2"
    const val VIDEOSHOT_API_URL = "https://api.bilibili.com/x/player/videoshot?index=1&bvid="
    const val FETCH_TICKET_URL = "https://api.bilibili.com/bapis/bilibili.api.ticket.v1.Ticket/GenWebTicket"
    const val SEARCH_BASE_URL = "https://api.bilibili.com/x/web-interface/search/type"
    const val DANMAKU_RAW_URL = "danmaku://bilibili.raw"
    const val LIVE_ROOM_INFO_INIT_API_URL = "https://api.live.bilibili.com/room/v1/Room/room_init?id="
    const val LIVE_ROOM_INFO_API_URL = "https://api.live.bilibili.com/room/v1/Room/get_status_info_by_uids?uids[]="
    const val LIVE_ROOM_PLAY_BASE_API_URL = "https://api.live.bilibili.com/xlive/web-room/v2/index/getRoomPlayInfo"
}